data:extend{
  {
    type = "int-setting",
    name = "greencircuit-asif-items-per-second",
    setting_type = "startup",
    minimum_value = 1,
    maximum_value = 100000,
    default_value = 1000,
    order = "a",
  },
  {
    type = "string-setting",
    name = "greencircuit-asif-recipe-variant",
    setting_type = "startup",
    default_value = "electronic-circuit-stone",
    allowed_values   = {"electronic-circuit","electronic-circuit-stone"},
    order = "a1"
  },
  {
    type = "int-setting",
    name = "redcircuit-asif-items-per-second",
    setting_type = "startup",
    minimum_value = 1,
    maximum_value = 100000,
    default_value = 1000,
    order = "b",
  },
  {
    type = "int-setting",
    name = "bluecircuit-asif-items-per-second",
    setting_type = "startup",
    minimum_value = 1,
    maximum_value = 100000,
    default_value = 1000,
    order = "c",
  },
  {
    type = "string-setting",
    name = "bluecircuit-asif-recipe-variant",
    setting_type = "startup",
    default_value = "se-processing-unit-holmium",
    allowed_values   = {"processing-unit","se-processing-unit-holmium"},
    order = "c1"
  },
  {
    type = "int-setting",
    name = "se-bc-asif-items-per-second",
    setting_type = "startup",
    minimum_value = 1,
    maximum_value = 100000,
    default_value = 1000,
    order = "c2",
  },
  {
    type = "int-setting",
    name = "lowdensitystructure-asif-items-per-second",
    setting_type = "startup",
    minimum_value = 1,
    maximum_value = 100000,
    default_value = 1000,
    order = "d",
  },
  {
    type = "string-setting",
    name = "lowdensitystructure-asif-recipe-variant",
    setting_type = "startup",
    default_value = "se-low-density-structure-beryllium",
    allowed_values   = {"low-density-structure","se-low-density-structure-beryllium"},
    order = "d1"
  },
  {
    type = "int-setting",
    name = "se-lds-asif-items-per-second",
    setting_type = "startup",
    minimum_value = 1,
    maximum_value = 100000,
    default_value = 1000,
    order = "d2",
  },
  {
    type = "int-setting",
    name = "heatshielding-asif-items-per-second",
    setting_type = "startup",
    minimum_value = 1,
    maximum_value = 100000,
    default_value = 1000,
    order = "e",
  },
  {
    type = "string-setting",
    name = "heatshielding-asif-recipe-variant",
    setting_type = "startup",
    default_value = "se-heat-shielding-iridium",
    allowed_values   = {"se-heat-shielding","se-heat-shielding-iridium"},
    order = "e1"
  },
  {
    type = "int-setting",
    name = "se-hsi-asif-items-per-second",
    setting_type = "startup",
    minimum_value = 1,
    maximum_value = 100000,
    default_value = 1000,
    order = "e2",
  },
  {
    type = "int-setting",
    name = "engine-asif-items-per-second",
    setting_type = "startup",
    minimum_value = 1,
    maximum_value = 100000,
    default_value = 1000,
    order = "f",
  },
  {
    type = "int-setting",
    name = "plastic-asif-items-per-second",
    setting_type = "startup",
    minimum_value = 1,
    maximum_value = 100000,
    default_value = 1000,
    order = "g",
  },
  {
    type = "int-setting",
    name = "rocketfuel-asif-items-per-second",
    setting_type = "startup",
    minimum_value = 1,
    maximum_value = 100000,
    default_value = 1000,
    order = "h",
  },
  {
    type = "string-setting",
    name = "rocketfuel-asif-recipe-variant",
    setting_type = "startup",
    default_value = "rocket-fuel",
    allowed_values   = {"rocket-fuel","se-vulcanite-rocket-fuel"},
    order = "h1"
  },
  {
    type = "int-setting",
    name = "solidfuel-petroleumgas-asif-items-per-second",
    setting_type = "startup",
    minimum_value = 1,
    maximum_value = 100000,
    default_value = 1000,
    order = "i",
  },
  {
    type = "int-setting",
    name = "solidfuel-lightoil-asif-items-per-second",
    setting_type = "startup",
    minimum_value = 1,
    maximum_value = 100000,
    default_value = 1000,
    order = "j",
  },
  {
    type = "int-setting",
    name = "solidfuel-heavyoil-asif-items-per-second",
    setting_type = "startup",
    minimum_value = 1,
    maximum_value = 100000,
    default_value = 1000,
    order = "k",
  },
  {
    type = "int-setting",
    name = "rocketcontrolunit-asif-items-per-second",
    setting_type = "startup",
    minimum_value = 1,
    maximum_value = 100000,
    default_value = 1000,
    order = "l",
  },
  {
    type = "int-setting",
    name = "spd-3-asif-items-per-second",
    setting_type = "startup",
    minimum_value = 1,
    maximum_value = 10000,
    default_value = 1000,
    order = "m",
  },
  {
    type = "int-setting",
    name = "prod-3-asif-items-per-second",
    setting_type = "startup",
    minimum_value = 1,
    maximum_value = 10000,
    default_value = 1000,
    order = "n",
  },
  {
    type = "int-setting",
    name = "eff-3-asif-items-per-second",
    setting_type = "startup",
    minimum_value = 1,
    maximum_value = 10000,
    default_value = 1000,
    order = "o",
  },
  {
    type = "int-setting",
    name = "oil-asif-ratio",
    setting_type = "startup",
    minimum_value = 21,
    maximum_value = 1000,
    default_value = 63,
    order = "p",
  },
  {
    type = "int-setting",
    name = "lightcracking-asif-ratio",
    setting_type = "startup",
    minimum_value = 33,
    maximum_value = 1000,
    default_value = 99,
    order = "q",
  },
  {
    type = "int-setting",
    name = "heavycracking-asif-ratio",
    setting_type = "startup",
    minimum_value = 9,
    maximum_value = 1000,
    default_value = 27,
    order = "r",
  },
  {
    type = "int-setting",
    name = "arty-shell-asif-items-per-second",
    setting_type = "startup",
    minimum_value = 1,
    maximum_value = 100000,
    default_value = 1000,
    order = "s",
  },
  {
    type = "int-setting",
    name = "beacon-asif-items-per-second",
    setting_type = "startup",
    minimum_value = 1,
    maximum_value = 100000,
    default_value = 1000,
    order = "t",
  },
  {
    type = "int-setting",
    name = "max-bld-size",
    setting_type = "startup",
    allowed_values = {31,39,49,57,67,75,85,93,103,111,121,129,139,147,157,165,175,183,193,201,211,219,229,237,247,255,265,273,283,291,301,309,319,327,337,345,355,363,373,381,391,399,409,417,427,435,445,453,463,471,481,489,499,507,517,525,535,543,553,561,571,579,589,597,607,615,625,633,643,651,661,669,679,687,697,705,715,723,733,741,751,759,769,777,787,795,805,813,823,831,841,849,859,867,877,885,895,903,913,921,931,939,949,957,967,975,985,993},
	default_value = 31,
    order = "z",
  },
  {
    type = "int-setting",
    name = "max-flow-rate",
    setting_type = "startup",
    minimum_value = 2000,
    maximum_value = 24000,
    default_value = 7200,
    order = "z2",
  },
  {
	type = "bool-setting",
	name = "ass-alt-map-color",
	setting_type = "startup",
	default_value = true,
	order = "z3",
  },
}
